const REQUEST_USER_DATA = "REQUEST_USER_DATA";
const RECIEVE_USER_DATA = "RECIEVE_USER_DATA";
const SIGN_IN_AS_GUEST = "SIGN_IN_AS_GUEST";

export default {
  REQUEST_USER_DATA,
  RECIEVE_USER_DATA,
  SIGN_IN_AS_GUEST
};
