const SEND_REQUEST = "SEND_REQUEST";
const RECIEVE_RESPONSE = "RECIEVE_RESPONSE";
const RECIEVE_SEARCH_RESULT = "RECIEVE_SEARCH_RESULT";
const RESET_SEARCH = "RESET_SEARCH";
const SIGN_IN = "SIGN_IN";
const SIGN_UP = "SIGN_UP";
const RECIEVE_USER_DATA = "RECIEVE_USER_DATA";
const SIGN_IN_AS_GUEST = "SIGN_IN_AS_GUEST";

export default {
  SEND_REQUEST,
  RECIEVE_RESPONSE,
  RECIEVE_SEARCH_RESULT,
  RESET_SEARCH,
  SIGN_IN,
  SIGN_UP,
  RECIEVE_USER_DATA,
  SIGN_IN_AS_GUEST
};
