const SAVE_CABLE = "SAVE_CABLE";
const SAVE_SUBSCRIPTION = "SAVE_SUBSCRIPTION";
const REQUEST_RATES = "REQUEST_RATES";
const RECIEVE_RATES = "RECIEVE_RATES";
const RESET = "RESET";

export default {
  SAVE_CABLE,
  SAVE_SUBSCRIPTION,
  REQUEST_RATES,
  RECIEVE_RATES,
  RESET
};
